before_install:
   - wget https://github.com/rebar/rebar/wiki/rebar
   - wget https://s3.amazonaws.com/rebar3/rebar3
   - chmod u+x ./rebar
   - chmod u+x ./rebar3
install: "true"
language: erlang
sudo: false
otp_release:
  - 21.0
  - 20.0
  - 19.0
  - 18.0
  - 17.0
env:
  - REBAR3=false
  - REBAR3=true
script: 
    - case "$REBAR3" in
        false) ./rebar compile && ./rebar skip_deps=true doc && ./rebar skip_deps=true eunit;;
        true) ./rebar3 do eunit,edoc;;
      esac
